version: '3'
services:
  rasa_en:
    image: rasa_core_latest
    build:
      context: .
    volumes:
      - ${PWD}/data:/app/data
    ports:
      - "5005:5005"
    command: python -m rasa_core.run -c rest -c facebook  -d data/Demo-Bot/models/core/KerasPolicy --endpoints endpoints.yml --credentials credentials.yml --debug
  action:  
    image: action_server
    build:
      context: ./actions
    volumes:
      - ${PWD}/actions:/app
    ports:
      - "5055:5055"
    command : python -m rasa_core_sdk.endpoint --actions actions 
  nlg:  
    image: nlg_server
    build:
      context: ./nlg
    volumes:
      - ${PWD}/data:/app/data
    ports:
      - "5056:5056"
    command : python nlg/nlg_server.py --port 5056 --domain data/Demo-Bot/domain.yml
  
