apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: action
  name: action
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: action
    spec:
      containers:
      - args:
        - python
        - -m
        - rasa_core_sdk.endpoint
        - --actions
        - actions
        image: action_server
        name: action
        ports:
        - containerPort: 5055
        resources: {}
      restartPolicy: Always
status: {}
