apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nlg
  name: nlg
spec:
  ports:
  - name: "5056"
    port: 5056
    targetPort: 5056
  selector:
    io.kompose.service: nlg
status:
  loadBalancer: {}
