apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nlg
  name: nlg
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nlg
    spec:
      containers:
      - args:
        - python
        - nlg/nlg_server.py
        - --port
        - "5056"
        - --domain
        - data/servicing-bot-en/domain.yml
        image: nlg_server
        name: nlg
        ports:
        - containerPort: 5056
        resources: {}
      restartPolicy: Always
status: {}
